export const INDEXING_SOURCES = [
  'Scopus',
  'Web of Science',
  'PubMed',
  'DOAJ',
  'Embase',
  'CINAHL',
  'PsycINFO',
  'ERIC',
  'Ei Compendex',
  'INSPEC',
  'MathSciNet',
  'EBSCO',
] as const;

export const SUBJECT_FIELD_OPTIONS = [
  'Agricultural and Biological Sciences',
  'Arts and Humanities',
  'Biochemistry, Genetics and Molecular Biology',
  'Business, Management and Accounting',
  'Chemical Engineering',
  'Chemistry',
  'Computer Science',
  'Decision Sciences',
  'Earth and Planetary Sciences',
  'Economics, Econometrics and Finance',
  'Energy',
  'Engineering',
  'Environmental Science',
  'Immunology and Microbiology',
  'Materials Science',
  'Mathematics',
  'Medicine',
  'Neuroscience',
  'Nursing',
  'Pharmacology, Toxicology and Pharmaceutics',
  'Physics and Astronomy',
  'Psychology',
  'Social Sciences',
  'Veterinary',
  'Dentistry',
  'Health Professions',
] as const;
